### ISSUE TITLE
Общие рекомендации

### ISSUE THREAD

**Issue by MariaGold** [AlexandraNasonova/air_pollution_predict#27]
Привет! Время уже поджимает, поэтому дам общие рекомендации. У вас вроде как много всего, но нет реализации FastAPI. Ее нужно добавить. Ваш сервис должен реализовывать основные запросы:

1. / - корневой роут должен отдавать, например, идентификатор текущей актуальной модели или какую-то информационную справку. Либо можно просто статус 200 и ОК.
2. /predict - делает предсказание либо по тем данным, что переданы в POST-запросе, либо по каким-то заранее загруженным
3. /evaluate - отдает метрики модели

В идеале каждая модель должна быть сохранена в onnx-формате. В onnx-файле можно хранить мета-данные, например, идентификатор модели, дату последнего обновления, метрики качества и т д. Также можно в роуты добавить метод переключения между моделями.

**Comment by AlexandraNasonova** [comment]
Привет! 
Все сделано. 
- Ветка, в которой велась разработка, теперь смержена в master, смотреть код можно там.
- Сохранение модели в ONNX формат сделано.
- Веб-сервис готов. 
- Docker готов. 
- прикручен DVC и внешнее S3 хранилище. 
- код отрефакторен и более-менее приведен в соотвтетсвие PEP 8.
- есть немного юнит-тестов здесь:
https://github.com/AlexandraNasonova/air_pollution_predict/tree/master/airpollpredictor/data_preprocessing/aqi_calculations/tests
и здесь:
https://github.com/AlexandraNasonova/air_pollution_predict/tree/master/airpollpredictor/data_preprocessing

- **Документация на сервис и docker:** https://github.com/AlexandraNasonova/air_pollution_predict/blob/master/docs/DOCKER_WEB_SERVICE_airpollpredictor.pdf


Модель все еще не очень хорошо работает,  так что пусть метрики не пугают.
Пока нет MLFlow, логгера (кроме самописного для скачивания данных) и мониторинга. 

Если будет возможность, я буду очень рада замечаниям по поводу структуры проекта, написания функций и проч., рекомендациям и любым другим комментариям.
